import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";

import "./globals.css";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { Variable } from "lucide-react";

const IBMPlex = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
  variable: '--font-ibm-plex'
});

export const metadata: Metadata = {
  title: "ArtifyX_AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
  appearance={{
    variables: { colorPrimary: '#624cf5' },
    elements: {
      logo: {
        width: '200px', // Set the desired width
        height: '100px', // Set the desired height
      },
    },
  }}
>
  <html lang="en">
    <body className={cn("font-IBMPlex antialiased", IBMPlex.variable)}>
      {children}
    </body>
  </html>
</ClerkProvider>
)}
